import { Award, Download, Send, Eye, Upload } from "lucide-react";
import { useState } from "react";

export default function AssessmentReports() {
  const [logoUploaded, setLogoUploaded] = useState(false);

  const assessmentData = {
    studentName: "Rahul Ahmed",
    studentId: "STD-2024-156",
    assessmentDate: "2026-05-14",
    counselor: "Mehedi Hasan",
    scores: {
      academicProfile: 85,
      languageProficiency: 78,
      financialReadiness: 92,
      documentationStatus: 88,
      overallScore: 86,
    },
    recommendations: [
      "Student shows strong academic background suitable for Canadian universities",
      "IELTS score of 7.0 meets most university requirements",
      "Financial documents are well-prepared and sufficient",
      "Recommended programs: Computer Science, Engineering, Business Analytics",
    ],
  };

  const recentReports = [
    { id: "RPT-156", student: "Rahul Ahmed", date: "2026-05-14", status: "Generated" },
    { id: "RPT-155", student: "Fatima Khan", date: "2026-05-13", status: "Sent" },
    { id: "RPT-154", student: "Sakib Hassan", date: "2026-05-12", status: "Generated" },
  ];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-semibold text-gray-900">White-Label Assessment Reports</h1>
        <p className="text-gray-500 mt-2">Generate assessment reports with your agency logo and branding</p>
      </div>

      {/* Branding Setup */}
      <div className="bg-gradient-to-br from-purple-500 to-purple-600 p-6 rounded-xl text-white">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-semibold mb-2">Your Agency Branding</h2>
            <p className="text-purple-100">Customize reports with your logo and center information</p>
          </div>
          <Award size={48} />
        </div>
        <div className="mt-6 flex gap-3">
          <button
            onClick={() => setLogoUploaded(true)}
            className="px-6 py-3 bg-white/20 hover:bg-white/30 rounded-lg transition-colors flex items-center gap-2"
          >
            <Upload size={18} />
            {logoUploaded ? "Change Logo" : "Upload Logo"}
          </button>
          {logoUploaded && (
            <div className="flex items-center gap-2 px-4 py-2 bg-white/20 rounded-lg">
              <Award size={18} />
              <span className="text-sm">Logo Uploaded</span>
            </div>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Assessment Preview */}
        <div className="lg:col-span-2 bg-white p-8 rounded-xl border border-gray-200">
          <div className="flex items-center justify-between mb-6 pb-4 border-b border-gray-200">
            <div>
              <h2 className="text-2xl font-semibold text-gray-900">Student Assessment Report</h2>
              <p className="text-sm text-gray-500 mt-1">Generated by Your Agency Name</p>
            </div>
            {logoUploaded && (
              <div className="w-16 h-16 bg-blue-100 rounded-lg flex items-center justify-center">
                <Award size={32} className="text-blue-600" />
              </div>
            )}
          </div>

          <div className="space-y-6">
            {/* Student Info */}
            <div className="grid grid-cols-2 gap-4 p-4 bg-gray-50 rounded-lg">
              <div>
                <p className="text-xs text-gray-500 mb-1">Student Name</p>
                <p className="font-medium text-gray-900">{assessmentData.studentName}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 mb-1">Student ID</p>
                <p className="font-medium text-gray-900">{assessmentData.studentId}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 mb-1">Assessment Date</p>
                <p className="font-medium text-gray-900">{assessmentData.assessmentDate}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 mb-1">Counselor</p>
                <p className="font-medium text-gray-900">{assessmentData.counselor}</p>
              </div>
            </div>

            {/* Overall Score */}
            <div className="text-center p-6 bg-gradient-to-br from-green-50 to-green-100 rounded-lg">
              <p className="text-sm text-gray-600 mb-2">Overall Assessment Score</p>
              <p className="text-6xl font-bold text-green-600 mb-2">{assessmentData.scores.overallScore}</p>
              <p className="text-sm font-medium text-green-700">Excellent Profile</p>
            </div>

            {/* Score Breakdown */}
            <div>
              <h3 className="font-semibold text-gray-900 mb-4">Score Breakdown</h3>
              <div className="space-y-3">
                {Object.entries(assessmentData.scores)
                  .filter(([key]) => key !== "overallScore")
                  .map(([key, value]) => (
                    <div key={key}>
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium text-gray-700 capitalize">
                          {key.replace(/([A-Z])/g, " $1").trim()}
                        </span>
                        <span className="text-sm font-semibold text-gray-900">{value}/100</span>
                      </div>
                      <div className="w-full bg-gray-200 rounded-full h-2">
                        <div
                          className="bg-blue-500 rounded-full h-2 transition-all"
                          style={{ width: `${value}%` }}
                        ></div>
                      </div>
                    </div>
                  ))}
              </div>
            </div>

            {/* Recommendations */}
            <div>
              <h3 className="font-semibold text-gray-900 mb-4">Professional Recommendations</h3>
              <ul className="space-y-3">
                {assessmentData.recommendations.map((rec, index) => (
                  <li key={index} className="flex items-start gap-3 text-sm text-gray-700">
                    <div className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-2 flex-shrink-0"></div>
                    {rec}
                  </li>
                ))}
              </ul>
            </div>

            {/* Signature Section */}
            <div className="pt-6 border-t border-gray-200">
              <div className="flex items-end justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-900">{assessmentData.counselor}</p>
                  <p className="text-xs text-gray-500">Senior Counselor</p>
                </div>
                <div className="text-right">
                  <p className="text-sm font-medium text-gray-900">Your Agency Name</p>
                  <p className="text-xs text-gray-500">Authorized Education Consultant</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Actions Panel */}
        <div className="space-y-4">
          <div className="bg-white p-6 rounded-xl border border-gray-200">
            <h3 className="font-semibold text-gray-900 mb-4">Report Actions</h3>
            <div className="space-y-2">
              <button className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
                <Download size={18} />
                Download PDF
              </button>
              <button className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors">
                <Send size={18} />
                Email to Student
              </button>
              <button className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors">
                <Eye size={18} />
                Preview
              </button>
            </div>
          </div>

          <div className="bg-white p-6 rounded-xl border border-gray-200">
            <h3 className="font-semibold text-gray-900 mb-4">Report Features</h3>
            <ul className="space-y-2 text-sm text-gray-600">
              <li className="flex items-center gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-green-500"></div>
                Your agency logo
              </li>
              <li className="flex items-center gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-green-500"></div>
                Custom branding colors
              </li>
              <li className="flex items-center gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-green-500"></div>
                Professional layout
              </li>
              <li className="flex items-center gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-green-500"></div>
                Digital signature
              </li>
              <li className="flex items-center gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-green-500"></div>
                Watermark protection
              </li>
            </ul>
          </div>
        </div>
      </div>

      {/* Recent Reports */}
      <div className="bg-white p-6 rounded-xl border border-gray-200">
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-lg font-semibold text-gray-900">Recent Assessment Reports</h2>
          <button className="text-sm text-blue-600 hover:text-blue-700 font-medium">View All</button>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Report ID</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Student Name</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {recentReports.map((report) => (
                <tr key={report.id} className="hover:bg-gray-50">
                  <td className="px-4 py-4 text-sm font-medium text-gray-900">{report.id}</td>
                  <td className="px-4 py-4 text-sm text-gray-700">{report.student}</td>
                  <td className="px-4 py-4 text-sm text-gray-700">{report.date}</td>
                  <td className="px-4 py-4">
                    <span className="inline-block px-2 py-1 text-xs font-medium bg-green-100 text-green-700 rounded">
                      {report.status}
                    </span>
                  </td>
                  <td className="px-4 py-4">
                    <div className="flex items-center gap-2">
                      <button className="p-2 hover:bg-gray-100 rounded-lg">
                        <Eye size={16} className="text-gray-600" />
                      </button>
                      <button className="p-2 hover:bg-gray-100 rounded-lg">
                        <Download size={16} className="text-gray-600" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
